assets/urls.py
from django import urls
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from rest_framework import routers


from . import views
from .views import HomePageView,DashBoardView,employees,employeerequests,employeeassetrequest,employeedetails,assets,assetdetails,addasset
addasset


app_name ="assets"


urlpatterns=[
    # path('api_auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    # Endpoints 
    path('api/assets/', views.AssetList.as_view()),
    path('api/departments/', views.DepartmentList.as_view()),
    path('api/employeeAssetRequest/', views.EmployeeAssetRequestList.as_view()),
    path('api/managerrequest/', views.ManagerRequestSerializerList.as_view()),
    path('api/employeeAsset/',views.EmployeeAssetSerializerList.as_view()),
    # path('api/emails/',views.EmailSerializerList.as_view()),
    path('api/',views.api_overview),


    path('update/department/<int:id>/',views.update_department,name='update_department'),
    path('departments/',views.departments,name='departments'), 
    path('addasset',views.addasset,name='assetform'),
    
    path('employeedetails/<int:id>', employeedetails,name='employeedetails'),
    path('delete_employee/<int:id>', views.delete_employee,name='delete_employee'),
    path('employeeassetrequest',views.employeeassetrequest,name='employeeassetrequest'),
    path('managerrequest/',views.managerrequest,name='managerrequest'),
    path('assetdetails/<int:id>', views.assetdetails,name='assetdetails'),
    path('delete_asset/<int:id>', views.delete_asset,name='delete_asset'),
    
    path('dashboard',DashBoardView,name='dashboard'),
    
    path('employees',views.employees,name='employees'),
    path('dept_employees',views.dept_employees,name='dept_employees'),
    path('dashboard',DashBoardView,name='dashboard'),
    path('manager_dashboard',views.managerDashBoardView,name='manager_dashboard'),
    path('employee_dashboard',views.employeeDashBoardView,name='employee_dashboard'),
    # path('employeedetails/<int:id>', views.employeedetails,name='employeedetails'),
    path('department_detail/<int:id>',views.department_detail,name='department_detail'),
 
    path('dept_assets/',views.dept_assets,name='dept_assets'),
    path('employee_assets/',views.employee_assets,name='employee_assets'),
  
    path('employeeassetrequest/',views.employeeassetrequest,name='employeeassetrequest'),
    path('assign_asset/<int:id>',views.assign_asset,name='assign_asset'),
    path('assign_asset_user/<int:id>',views.assign_asset_user,name='assign_asset_user'),
    path('unassign_asset_user/<int:id>',views.unassign_asset_user,name='unassign_asset_user'),
    path('unassign_asset_dept/<int:id>',views.unassign_asset_dept,name='unassign_asset_dept'),
    # path('employeedetails/<int:id>', views.employeedetails,name='employeedetails'),
    path('department_detail/<int:id>',views.department_detail,name='department_detail'),
    path('delete_department/<int:id>',views.delete_department,name='delete_department'),
    path('assets/',views.assets,name='assets'),
    path('update_asset/<int:id>/',views.update_asset,name='update_asset'),
    path('employeeassetrequest/',views.employeeassetrequest,name='employeeassetrequest'),
    
    path('assign_asset/<int:id>',views.assign_asset,name='assign_asset'),
    
    path('',views.request_demo,name='request_demo'),
    
    path('assign_asset/<int:id>',views.assign_asset,name='assign_asset'),
    path('dept_requests',views.dept_requests,name='dept_requests'),
    path('employee_requests',views.employee_requests,name='employee_requests'),
    path('employeerequestdetails/<int:id>', views.employeerequestdetails,name='employeerequestdetails'),
    path('managerrequestdetails/<int:id>', views.managerrequestdetails ,name='managerrequestdetails'),
    path('update_manager_request/<int:id>', views.update_manager_request ,name='update_manager_request'),
    path('update_employee_request/<int:id>', views.update_employee_request ,name='update_employee_request'),
    path('delete_employee_request/<int:id>', views.delete_employee_request ,name='delete_employee_request'),
    path('delete_manager_request/<int:id>', views.delete_manager_request ,name='delete_manager_request'),
    path('requests', views.requests,name='requests'),
    path('add_departments/',views.add_departments,name='add_departments'),
    path('employee_assets',views.employee_assets,name='employee_assets'),
    path('api/asset/', views.AssetList.as_view()),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import(
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView
    
    )
from users.views import SignupView
from assets import views as user_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("assets.urls")),
    path('profile/', user_views.profile, name='profile'),
    path('profile_page/', user_views.profile_page, name='profile_page'),
    # path('signup/',SignupView.as_view(),name='signup'),
    path('signup/',SignupView,name='signup'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page = 'login'),name='logout')


]

assets/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from .models import  Department, Asset,EmployeeAssetRequest,ManagerRequest,EmployeeAsset
from .models import  Department, Asset,EmployeeAssetRequest,ManagerRequest,EmployeeAsset,Profile,User


class EmployeeProfile(forms.ModelForm):
    class Meta:
        model=Profile
        fields= ('department','role')
        
class DepartmentForm(forms.ModelForm):
    class Meta:
        model=Department
        fields= ('name','description')

class AssetForm(forms.ModelForm):
    class Meta:
        model=Asset
        fields= ('name','description','image','category',)

class EmployeeAssetRequestForm(forms.ModelForm):
    class Meta:
        model=EmployeeAssetRequest
        fields= ('type','request_detail','quantity','urgency')

class ManagerRequestForm(forms.ModelForm):
    class Meta:
        model=ManagerRequest
        fields= ('request','specs','quantity','urgency')

class DepartmentAssigningForm(forms.ModelForm):
    class Meta:
        model=Department
        fields= ('manager',)

class AssetAssigningForm(forms.ModelForm):
    class Meta:
        model=Asset
        fields= ('department',)

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email',]

class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image', 'bio', 'phone' ]

class EmployeeRequest(forms.ModelForm):
    class Meta:
        model=EmployeeAssetRequest
        fields= ('status',)
class ManagerRequestUpdateForm(forms.ModelForm):
    class Meta:
        model=ManagerRequest
        fields= ('status',)
        

class EmailForm(forms.Form):
    full_name = forms.CharField(label='First Name',max_length=30)
    email = forms.EmailField(label='Email')
    account_specifications = forms.CharField(label='Account Specifications')

assets/views.py
from django import forms
from django.http.response import HttpResponseRedirect
from django.shortcuts import render,reverse,redirect
from django.contrib import messages

from .forms import UserUpdateForm, ProfileUpdateForm, EmailForm
from assets.models import Profile
from django.db.models import manager
from django.shortcuts import render,reverse,redirect,get_object_or_404
from django.contrib.auth import login, authenticate
from django.http import Http404,HttpResponse
from django.conf import settings
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.decorators import api_view



from . models import EmployeeAsset,EmployeeAssetRequest,Department,Asset,ManagerRequest,Profile
from . forms import DepartmentForm,AssetForm,EmployeeAssetRequestForm,ManagerRequestForm,AssetAssigningForm,DepartmentAssigningForm,EmployeeProfile,EmployeeRequest,ManagerRequestUpdateForm
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import AssetSerializer,EmployeeAssetRequestSerializer,DepartmentSerializer,ManagerRequestSerializer,EmployeeAssetSerializer
from rest_framework import status
from assets import serializers


import sys
sys.path.append("..")
from users.models import User
# third party imports

from django.views import generic 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# from .email import send_welcome_email
import datetime as dt


# class DepartmentViewSet(viewsets.ModelViewSet):
#     queryset = Department.objects.all().order_by('name')
#     serializer_class = DepartmentSerializer



def HomePageView(request):
    return render(request,'assets/home.html')


def  DashBoardView(request):
        try:
            department= Department.objects.get(manager=request.user.id)
            dept_assets=Asset.objects.filter(department=department)
            dept_employees=Profile.objects.filter(department=department)
        except Department.DoesNotExist:
            department=[]
            dept_assets=[]
            dept_employees=[]
     
        if request.user.is_admin:
            return redirect('assets:manager_dashboard')
        
        if not request.user.is_admin and not request.user.is_superuser:
            return redirect('assets:employee_dashboard')
        
        total_asset = Asset.objects.count()
        total_department = Department.objects.count()
        total_user = User.objects.count()  
        date = dt.date.today() 
        
        managers = Profile.objects.filter(role="Admin")
        assigned_assets=Asset.objects.filter(is_assigned_dept=True)
        unassigned_assets=Asset.objects.filter(is_assigned_dept=False)
        manager_requests= ManagerRequest.objects.count()
        uncompleted_manager_request=ManagerRequest.objects.filter(status="pending")
        employee_requests= EmployeeAssetRequest.objects.count()
        uncompleted_employee_request=EmployeeAssetRequest.objects.filter(status="pending")
        # messages.success(request,"Congrats young padawan")   

        context = {
        'assets': total_asset,
        'departments': total_department,
        'manager_requests':manager_requests,
        'uncompleted_manager_request': uncompleted_manager_request,
        'employee_requests':employee_requests,
        'uncompleted_employee_request': uncompleted_employee_request,
        'managers':managers,
        'assigned_assets': assigned_assets,
        'unassigned_assets':unassigned_assets,
        'employees' : total_user,
        'dept_assets':dept_assets,
        'dept_employees': dept_employees,
        "date":date
        
        # "messages":messages
            
        }
        return render(request,'assets/dashboard.html',context)
def  employeeDashBoardView(request):
        user=Profile.objects.get(user=request.user)
        assets = EmployeeAsset.objects.filter(employee__user=request.user.id) 
        employee_requests= EmployeeAssetRequest.objects.filter(employee=user)
        employee_requests_undone= EmployeeAssetRequest.objects.filter(employee=user,status="pending")
        date = dt.date.today() 
        context = {
        'assets': assets,    
          "date":date ,
          "employee_requests_undone":employee_requests_undone ,
          "employee_requests": employee_requests,
           
        }
        return render(request,'assets/employee_dashboard.html',context)
    
def  managerDashBoardView(request):
        user=Profile.objects.get(user=request.user)
        manager_requests= ManagerRequest.objects.filter(employee=user)
        department= Department.objects.get(manager=request.user.id)
        
        dept_assets=Asset.objects.filter(department=department)
        dept_assets_assigned=Asset.objects.filter(department=department,is_assigned_user=True)
        dept_assets_unassigned=Asset.objects.filter(department=department,is_assigned_user=False)
        
        dept_employee_requests= EmployeeAssetRequest.objects.filter(employee__department=department)
        dept_employee_requests_undone= EmployeeAssetRequest.objects.filter(employee__department=department,status="pending")
        
        dept_employees=Profile.objects.filter(department=department)
        date = dt.date.today() 
        context = {
    
        'department':department,
        'manager_requests':manager_requests,
        'dept_assets':dept_assets,
        'dept_employees': dept_employees,
          "date":date,
          "dept_assets_assigned": dept_assets_assigned,
          "dept_assets_unassigned": dept_assets_unassigned,
          "dept_employee_requests":dept_employee_requests,
          "dept_employee_requests_undone":dept_employee_requests_undone
          
          
        
        }
        return render(request,'assets/managerDashboard.html',context)



def addasset(request):
   
    if request.method == 'POST':
        form=AssetForm(request.POST,request.FILES)
        if form.is_valid():
            asset = form.save(commit=False)
            asset.save()
            return redirect('assets:assets')
    else:
        form=AssetForm()
    params={
        'form':form
    }
    return render(request,'assets/addasset.html', params)

def assets(request):
    if request.user.is_admin:
            return redirect('assets:dept_assets')
        
    if not request.user.is_admin and not request.user.is_superuser:
            return redirect('assets:employee_assets')
    
    assets=Asset.objects.all()
    user=User.objects.get(id=request.user.id)
    print(user)
    form=AssetForm()
    
    if request.method == 'POST':
        form=AssetForm(request.POST,request.FILES)
        if form.is_valid():
            asset = form.save(commit=False)
            asset.save()
            return redirect('assets:assets')
    else:
        form=AssetForm()
    
    params= {'assets': assets,'form':form,'user':user}
    return render(request,'assets/assets.html', params)

def dept_assets(request):
    department= Department.objects.get(manager=request.user.id)
    dept_assets=EmployeeAsset.objects.filter(asset__department=department)
    user=User.objects.get(id=request.user.id)
    print(dept_assets)
    
    params= {'dept_assets': dept_assets,'user':user}
    return render(request,'assets/departmentAsset.html',params)

def employee_assets(request):
    assets = EmployeeAsset.objects.filter(employee__user=request.user.id) 
    context = {
        'assets': assets,        
        }
    return render(request,'assets/employee_assets.html', context)

def assetdetails(request,id):
    asset=Asset.objects.get(id=id)
    form = AssetForm(instance = asset)
    params={
        'asset':asset,
        'form':form
        
    }
    return render(request,'assets/assetdetails.html', params)

def update_asset(request, id):
    asset_id = int(id)
    try:
        asset = Asset.objects.get(id = asset_id)
    except Asset.DoesNotExist:
        return redirect('assets:assets')
    form = AssetForm(request.POST or None, instance = asset)
    if form.is_valid():
        form.save()
        return redirect('assets:assets')

   

def assign_asset(request,id):
    asset=Asset.objects.get(id=id)
    form =AssetAssigningForm(instance = asset)
    if request.method == 'POST':
        form=AssetAssigningForm(request.POST,instance = asset)
        if form.is_valid():
            asset = form.save(commit=False)
            asset.is_assigned_dept = True
            asset.save()
            return redirect('assets:assets')
    else:
        form=AssetAssigningForm()

    params={
        'form':form,
        'asset':asset
    }
    return render(request,'assets/assignasset.html', params)

def assign_asset_user(request,id):
    asset= EmployeeAsset.objects.get(asset_id=id)
    assigned_asset=Asset.objects.get(id=id)
    employees = Profile.objects.filter(department=asset.asset.department)
    if request.method == 'POST':
        
            name= request.POST.get('employee')
            employee = Profile.objects.get(user__username=name)
           
            assigned_asset.is_assigned_user=True
            assigned_asset.save()
            
            asset.employee=employee
            asset.save()
            return redirect('assets:dept_assets')
    else:
        print('')

    params={
        'employees':employees,
        'asset':asset
    }
    return render(request,'assets/assignuserasset.html', params)

def unassign_asset_user(request,id):
    asset= EmployeeAsset.objects.get(asset_id=id)
    assigned_asset=Asset.objects.get(id=id)
    assigned_asset.is_assigned_user=False
    assigned_asset.save()
            
    asset.employee=None
    asset.save()
    return redirect('assets:dept_assets')
def unassign_asset_dept(request,id):
    
    try:
        asset= EmployeeAsset.objects.get(asset_id=id)
    except Asset.DoesNotExist:
        print("")
    assigned_asset=Asset.objects.get(id=id)

assets/templates/assets/apdatedep.html
{%extends 'assets/base.html'%}
<!-- bootstrap -->
{% load static%}
{% load bootstrap4 %}
<!-- html -->
{% block content %}
<!-- content -->
<div class="container-fluid p-4">
  <h1 class="text-center text-success">Form trial rendering</h1>

  <hr>

  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h2>Adding Departments</h2>
      <h3>Forms</h3>
      <form class="form" action="" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form form layout='block' %}
        <button type="submit" class="btn btn-sm btn-primary" style="margin-top:10px; margin-left:5px">Add</button>
      </form>
    </div>




    <div class="col-md-3"></div>

  </div>
  <hr>
  
</div>
{% endblock%}

assets/templates/assets/departments.html
{%extends 'assets/base.html'%} {% load bootstrap4%} {% load static %}
<!-- content -->
{%block content%}

<div class="ml-5 mr-5 pt-2 pr-5">
  <div class="intro mt-3">
    <header class="mb-3 p-0">
      <h1 class="m-0 p-0">DEPARTMENTS</h1>

      <div>
        <a
          href="/add_department"
          class="btn btn-success"
          data-toggle="modal"
          data-target="#staticBackdrop"
        >
          Add Department</a
        >
      </div>
    </header>
  </div>

  <div class="text-center">
    <div>
      <div class="icon-wrap m-3" style="height: 100px">
        <img
          style="height: 100%"
          src="../../static/icons/department(1).png"
          alt=""
        />
      </div>
    </div>
  </div>

  <!-- <p class="m-0 p-0">
    We ensure that all assets in departments are physically safeguarded and
    properly accounted for in our organization asset records
  </p> -->

  <div class="departments mt-3">
    <div class="row">
      {%for department in department%}

      <a
        href="{%url 'assets:department_detail' department.id%}"
        class="col-md-3 dep-card m-3 mt-5"
      >
        <h3 style="text-transform: capitalize">{{department.name}}</h3>

        <h5>
          Manager : {% if department.manager %}
          <span style="text-transform: capitalize"
            >{{department.manager}}
          </span>

          <!-- option -->
          {% endif %}
        </h5>

        <h4 class="dep_description text-muted">{{department.description}}</h4>
      </a>

      <!-- <div class="col-6">
        <a href="/department_detail/{{department.id}}">
          <div class="card h-100">
            <div class="card-body">
              <h5 class="card-title text-success text-center">
                {{department.name}}
              </h5>
              <p class="card-text">{{department.description}}</p>
              <p class="card-title">
                <mark>Head of Department {{department.manager}}</mark>
              </p>
            </div>
            <div class="card-footer">
              <small class="text-muted">{{department.created_at}}</small>
            </div>
          </div>
        </a>
      </div> -->
      {%endfor%}
    </div>
  </div>
</div>

<!-- add department modal -->
<div
  class="modal  fade"
  id="staticBackdrop"
  data-backdrop="static"
  data-keyboard="false"
  tabindex="-1"
  aria-labelledby="staticBackdropLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Department</h5>
        <button
          type="button"
          class="close text-white"
          data-dismiss="modal"
          aria-label="Close"
        >
          &times;
        </button>
      </div>
      <div class="modal-body">
        <form
          class="form"
          method="post"
          novalidate
          enctype="multipart/form-data"
        >
          {% csrf_token %} {% bootstrap_form form layout='block' %}
          <button type="submit" class="btn btn-success">Add</button>
        </form>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

​ {% endblock %}

assets/templates/assets/employeeRrequests.html
{%extends 'assets/base.html'%}
<!-- bootstrap -->
{% load bootstrap4%}
<!-- static -->
{% load static %}

<!-- content -->
{%block content%} ​

<div class="container">



  <div class="row">

    <div class="col-md-8">
      <h2 class="mt-4">My Requests</h2>
      <a href="/add_request" class="btn btn-success" data-toggle="modal" data-target="#staticBackdrop">
        Add Request</a>




      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Request</th>
            <th scope="col">Posted_date</th>
            <th scope="col">Quantity</th>
            <th scope="col">Urgency</th>
            <th scope="col">Status</th>

          </tr>
        </thead>


        {% for request in requests %}


        <tbody>
          <tr onclick="window.location='/employeerequestdetails/{{request.id}}'">

            <th scope="row">{{ request.id}}</th>
            <td>{{ request.request_detail }}({{ request.type }})</td>
            <td>{{ request.posted_date | date }}</td>
            <td>{{ request.quantity }} </td>
            <td>
                {% if request.status == "approved" %}
                         
                           <button class="btn btn-success">{{request.status }}</button>
                     
                           {%elif request.status == "rejected" %}
                          
 <button class="btn btn-danger">{{request.status }}</button>
                           
 
                           {%elif request.status == "pending" %}
                         
 <button class="btn btn-warning">{{request.status }}</button>

 {%else%}

                         {% endif %}
               
            </td>

            <!-- <td> <a href="delete/{{ request.id }}" class="btn btn-danger">Delete request</a> -->

            </td>
          </tr>


        </tbody>
        {% endfor %}
      </table>
    </div>
  </div>
</div>

<!-- modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Request</h5>
        <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
          &times;
        </button>
      </div>

      <div class="modal-body">
        <form class="form" method="post" novalidate enctype="multipart/form-data">
          {% csrf_token %} {% bootstrap_form form layout='block' %}
          <button type="submit" class="btn btn-success">Add</button>
        </form>
      </div>

    </div>
  </div>
</div>
{% endblock%}

assets/templates/assets/employee_assets.html
{%extends 'assets/base.html'%} {% load bootstrap4%} {% load static %}
<!-- content -->
{%block content%}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-12">
      <div class="intro mt-3">
        <header class="mb-3 p-0">
          <h2 class="">Employee assets</h2>

          <div></div>
        </header>
      </div>

      <table class="table mt-5">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Picture</th>
            <th scope="col">Description</th>
            <th scope="col">received on</th>
          </tr>
        </thead>

        {% for asset in assets %}

        <tbody>
          <tr>
            <th scope="row">{{ asset.id }}</th>
            <td>{{ asset.asset.name }}</td>
            <td>
              <img src="{{asset.asset.image.url}}" alt="" />
            </td>
            <td>{{ asset.asset.description }}</td>
            <td>{{ asset.asset.created_at |date }}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

{% endblock%}

assets/templates/assets/manager_request.html
{%extends 'assets/base.html'%}
<!-- bootstrap -->
{% load static%}
{% load bootstrap4 %}
<!-- html -->
{% block content %}
<!-- content -->
<div class="container-fluid p-4">
​
  <hr>
​
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h2>Manager Request</h2>
      <form class="form" action="" method="post" novalidate enctype="multipart/form-data">
        {% csrf_token %}
​
        {% bootstrap_form form layout='block' %}
        <button type="submit" class="btn btn-sm btn-primary" style="margin-top:10px; margin-left:5px">Submit</button>
      </form>
    </div>
​
​
​
    <div class="col-md-3"></div>
​
  </div>
</div>
{% endblock%}

assets/templates/assets/managerrequestdetails.html
{%extends 'assets/base.html'%} {% load bootstrap4%} {% load static %}
<!-- content -->
{%block content%}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-4">

  <div class="intro mt-3">
    <header class="mb-3 p-0">
      <h2>Manager Request Details</h2>

      <div>
         {% if user.is_superuser%}

        <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#staticBackdrop">Update</a>
        {% endif%}
        <div>
          {% if user == manager_requests.employee.user %}
          <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#staticBackdrop2">Update</a>

          <a class="btn btn-danger" href="#" data-toggle="modal" data-target="#staticBackdrop3">delete</a>
          {% endif %}
      </div>
    </header>
  </div>


    

      <hr>

      <div class="row">
      



        <div class="col-md-8 m-4">
          <div class="card card-body " >
           
            <div class="card-title">
              <header class="p-0 m-0">
                <div>
                   <h4>Request:</h4>
              <p>
                {{ manager_requests.request}}
              </p>
                </div>
                 <h4>{{ manager_requests.employee.user.username}}</h4>
              </header>
             

              <h4>Specifications:</h4>
              <p>
                {{ manager_requests.specs}}
              </p>

              <h5>Quantity: <strong>{{ manager_requests.quantity }}</strong></h5>
              <h5>Request date: <span>{{ manager_requests.posted_date |  date }}</span></h5>
              <h4>Status:

                     {% if manager_requests.status == "approved" %}
                         
                           <button class="btn btn-sm btn-success">{{manager_requests.status }}</button>
                     
                           {%elif manager_requests.status == "rejected" %}
                          
 <button class="btn btn-sm btn-danger">{{manager_requests.status }}</button>
                           
 
                           {%elif manager_requests.status == "pending" %}
                         
 <button class="btn btn-sm btn-warning">{{manager_requests.status }}</button>

 {%else%}

                         {% endif %}
              </h4>






              </ul>
            </div>
          </div>
        </div>

        <div class="col-md-5"></div>
      </div>

      <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Update Requests</h5>
              <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                &times;
              </button>
            </div>
            <div class="modal-body">
              <form class="form" method="post" novalidate enctype="multipart/form-data">
                {% csrf_token %}
                <!-- form2 -->
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-success">Update</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id="staticBackdrop2" data-backdrop="static" data-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Update Requests</h5>
              <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                &times;
              </button>
            </div>
            <div class="modal-body">
              <form class="form" action="{%url 'assets:update_manager_request' manager_requests.id %}" method="post"
                novalidate enctype="multipart/form-data">
                {% csrf_token %}
                <!-- form2 -->
                {% bootstrap_form form2 %}
                <button type="submit" class="btn btn-success">Update</button>
              </form>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="staticBackdrop3" data-backdrop="static" data-keyboard="false" tabindex="-1"
        aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete Request</h5>
              <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                &times;
              </button>
            </div>
            <div class="modal-body">
              <h4>Are you sure you want to delete this request?</h4>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-danger" data-dismiss="modal">
                Close
              </button>
              <a href="{%url 'assets:delete_manager_request' manager_requests.id%}" type="button"
                class="btn btn-primary">Confirm</a>
            </div>
          </div>
        </div>
      </div>

      {% endblock%}
    </div>